export const MENU_REGISTRY = Object.freeze([
  {
    key: "dashboard",
    label: "Dashboard",
    path: "/dashboard",
    icon: "LayoutDashboard",
    sortOrder: 10,
    requiredAnyPermissions: ["dashboard.view"],
    children: [],
  },

  {
    key: "student-management",
    label: "Student Management",
    path: null,
    icon: "GraduationCap",
    sortOrder: 40,
    requiredAnyPermissions: ["student.view", "student_field_config.view"],
    children: [
      {
        key: "students",
        label: "Students",
        path: "/students",
        icon: "GraduationCap",
        sortOrder: 10,
        requiredAnyPermissions: ["student.view"],
      },
      {
        key: "student-field-config",
        label: "Student Field Config",
        path: "/student-field-config",
        icon: "SlidersHorizontal",
        sortOrder: 20,
        requiredAnyPermissions: ["student_field_config.view"],
      },
    ],
  },

  {
    key: "attendance",
    label: "Attendance",
    path: null,
    icon: "CalendarDays",
    sortOrder: 50,
    requiredAnyPermissions: ["attendance.view", "attendance.mark"],
    children: [
      {
        key: "daily-attendance",
        label: "Daily Attendance",
        path: "/attendance/daily",
        icon: "CalendarDays",
        sortOrder: 10,
        requiredAnyPermissions: ["attendance.view", "attendance.mark"],
      },
      {
        key: "attendance-analytics",
        label: "Attendance Analytics",
        path: "/attendance/analytics",
        icon: "BarChart3",
        sortOrder: 20,
        requiredAnyPermissions: ["attendance.view"],
      },
      {
        key: "attendance-reports",
        label: "Attendance Reports",
        path: "/attendance/reports",
        icon: "FileSpreadsheet",
        sortOrder: 30,
        requiredAnyPermissions: ["attendance.view", "attendance.export"],
      },
      {
        key: "attendance-period-reports",
        label: "Monthly / Yearly Reports",
        path: "/attendance/period-reports",
        icon: "FileSpreadsheet",
        sortOrder: 40,
        requiredAnyPermissions: ["attendance.view", "attendance.export"],
      },
    ],
  },

  {
    key: "user-management",
    label: "User Management",
    path: null,
    icon: "Users",
    sortOrder: 70,
    requiredAnyPermissions: ["user.view", "role.view", "permission.view"],
    children: [
      {
        key: "users",
        label: "Users",
        path: "/users",
        icon: "UserRound",
        sortOrder: 10,
        requiredAnyPermissions: ["user.view"],
      },
      {
        key: "roles",
        label: "Roles & Permissions",
        path: "/roles",
        icon: "ShieldCheck",
        sortOrder: 20,
        requiredAnyPermissions: ["role.view", "role.manage_permissions"],
      },
      {
        key: "permission-catalog",
        label: "Permission Catalog",
        path: "/permissions",
        icon: "KeyRound",
        sortOrder: 30,
        requiredAnyPermissions: ["permission.view"],
      },
    ],
  },
  {
    key: "backups",
    label: "Backups",
    path: "/backups",
    icon: "DatabaseBackup",
    sortOrder: 90,
    requiredAnyPermissions: ["dashboard.view"],
    children: [],
  },
  {
    key: "settings",
    label: "Settings",
    path: null,
    icon: "Settings",
    sortOrder: 100,
    requiredAnyPermissions: [
      "academic_session.view",
      "class.view",
      "section.view",
    ],
    children: [
      {
        key: "academic-sessions",
        label: "Academic Sessions",
        path: "/settings/academic-sessions",
        icon: "CalendarDays",
        sortOrder: 10,
        requiredAnyPermissions: ["academic_session.view"],
      },
      {
        key: "classes",
        label: "Classes",
        path: "/settings/classes",
        icon: "School",
        sortOrder: 20,
        requiredAnyPermissions: ["class.view"],
      },
      {
        key: "sections",
        label: "Sections",
        path: "/settings/sections",
        icon: "PanelTop",
        sortOrder: 30,
        requiredAnyPermissions: ["section.view"],
      },
    ],
  },
]);
