export const PERMISSIONS = Object.freeze([
  {
    module: "Dashboard",
    moduleKey: "dashboard",
    action: "View",
    actionKey: "view",
    permissionKey: "dashboard.view",
    description: "Can view dashboard",
    menuGroup: "Dashboard",
    isMenuPermission: true,
    displayOrder: 10,
  },

  {
    module: "User Management",
    moduleKey: "user",
    action: "View",
    actionKey: "view",
    permissionKey: "user.view",
    description: "Can view users",
    menuGroup: "User Management",
    isMenuPermission: true,
    displayOrder: 100,
  },
  {
    module: "User Management",
    moduleKey: "user",
    action: "Create",
    actionKey: "create",
    permissionKey: "user.create",
    description: "Can create users",
    menuGroup: "User Management",
    isMenuPermission: false,
    displayOrder: 101,
  },
  {
    module: "User Management",
    moduleKey: "user",
    action: "Edit",
    actionKey: "edit",
    permissionKey: "user.edit",
    description: "Can edit users",
    menuGroup: "User Management",
    isMenuPermission: false,
    displayOrder: 102,
  },
  {
    module: "User Management",
    moduleKey: "user",
    action: "Delete",
    actionKey: "delete",
    permissionKey: "user.delete",
    description: "Can delete users",
    menuGroup: "User Management",
    isMenuPermission: false,
    displayOrder: 103,
  },
  {
    module: "User Management",
    moduleKey: "user",
    action: "Disable",
    actionKey: "disable",
    permissionKey: "user.disable",
    description: "Can disable users",
    menuGroup: "User Management",
    isMenuPermission: false,
    displayOrder: 104,
  },
  {
    module: "User Management",
    moduleKey: "user",
    action: "Reset Password",
    actionKey: "reset_password",
    permissionKey: "user.reset_password",
    description: "Can reset user passwords",
    menuGroup: "User Management",
    isMenuPermission: false,
    displayOrder: 105,
  },
  {
    module: "User Management",
    moduleKey: "user",
    action: "View Sessions",
    actionKey: "view_sessions",
    permissionKey: "user.view_sessions",
    description: "Can view active user sessions",
    menuGroup: "User Management",
    isMenuPermission: false,
    displayOrder: 106,
  },
  {
    module: "User Management",
    moduleKey: "user",
    action: "Force Logout",
    actionKey: "force_logout",
    permissionKey: "user.force_logout",
    description: "Can force logout users",
    menuGroup: "User Management",
    isMenuPermission: false,
    displayOrder: 107,
  },

  {
    module: "Role Management",
    moduleKey: "role",
    action: "View",
    actionKey: "view",
    permissionKey: "role.view",
    description: "Can view roles",
    menuGroup: "User Management",
    isMenuPermission: true,
    displayOrder: 200,
  },
  {
    module: "Role Management",
    moduleKey: "role",
    action: "Manage Permissions",
    actionKey: "manage_permissions",
    permissionKey: "role.manage_permissions",
    description: "Can manage role permissions",
    menuGroup: "User Management",
    isMenuPermission: false,
    displayOrder: 201,
  },

  {
    module: "Permission Management",
    moduleKey: "permission",
    action: "View",
    actionKey: "view",
    permissionKey: "permission.view",
    description: "Can view permission catalog",
    menuGroup: "User Management",
    isMenuPermission: false,
    displayOrder: 300,
  },

  {
    module: "Academic Sessions",
    moduleKey: "academic_session",
    action: "View",
    actionKey: "view",
    permissionKey: "academic_session.view",
    description: "Can view academic sessions",
    menuGroup: "Settings",
    isMenuPermission: true,
    displayOrder: 400,
  },
  {
    module: "Academic Sessions",
    moduleKey: "academic_session",
    action: "Create",
    actionKey: "create",
    permissionKey: "academic_session.create",
    description: "Can create academic sessions",
    menuGroup: "Settings",
    isMenuPermission: false,
    displayOrder: 401,
  },
  {
    module: "Academic Sessions",
    moduleKey: "academic_session",
    action: "Edit",
    actionKey: "edit",
    permissionKey: "academic_session.edit",
    description: "Can edit academic sessions",
    menuGroup: "Settings",
    isMenuPermission: false,
    displayOrder: 402,
  },
  {
    module: "Academic Sessions",
    moduleKey: "academic_session",
    action: "Delete",
    actionKey: "delete",
    permissionKey: "academic_session.delete",
    description: "Can delete academic sessions",
    menuGroup: "Settings",
    isMenuPermission: false,
    displayOrder: 403,
  },
  {
    module: "Academic Sessions",
    moduleKey: "academic_session",
    action: "Set Current",
    actionKey: "set_current",
    permissionKey: "academic_session.set_current",
    description: "Can set current academic session",
    menuGroup: "Settings",
    isMenuPermission: false,
    displayOrder: 404,
  },

  {
    module: "Classes",
    moduleKey: "class",
    action: "View",
    actionKey: "view",
    permissionKey: "class.view",
    description: "Can view classes",
    menuGroup: "Settings",
    isMenuPermission: true,
    displayOrder: 500,
  },
  {
    module: "Classes",
    moduleKey: "class",
    action: "Create",
    actionKey: "create",
    permissionKey: "class.create",
    description: "Can create classes",
    menuGroup: "Settings",
    isMenuPermission: false,
    displayOrder: 501,
  },
  {
    module: "Classes",
    moduleKey: "class",
    action: "Edit",
    actionKey: "edit",
    permissionKey: "class.edit",
    description: "Can edit classes",
    menuGroup: "Settings",
    isMenuPermission: false,
    displayOrder: 502,
  },
  {
    module: "Classes",
    moduleKey: "class",
    action: "Delete",
    actionKey: "delete",
    permissionKey: "class.delete",
    description: "Can delete classes",
    menuGroup: "Settings",
    isMenuPermission: false,
    displayOrder: 503,
  },

  {
    module: "Sections",
    moduleKey: "section",
    action: "View",
    actionKey: "view",
    permissionKey: "section.view",
    description: "Can view sections",
    menuGroup: "Settings",
    isMenuPermission: true,
    displayOrder: 600,
  },
  {
    module: "Sections",
    moduleKey: "section",
    action: "Create",
    actionKey: "create",
    permissionKey: "section.create",
    description: "Can create sections",
    menuGroup: "Settings",
    isMenuPermission: false,
    displayOrder: 601,
  },
  {
    module: "Sections",
    moduleKey: "section",
    action: "Edit",
    actionKey: "edit",
    permissionKey: "section.edit",
    description: "Can edit sections",
    menuGroup: "Settings",
    isMenuPermission: false,
    displayOrder: 602,
  },
  {
    module: "Sections",
    moduleKey: "section",
    action: "Delete",
    actionKey: "delete",
    permissionKey: "section.delete",
    description: "Can delete sections",
    menuGroup: "Settings",
    isMenuPermission: false,
    displayOrder: 603,
  },

  {
    module: "Students",
    moduleKey: "student",
    action: "View",
    actionKey: "view",
    permissionKey: "student.view",
    description: "Can view students",
    menuGroup: "Student Management",
    isMenuPermission: true,
    displayOrder: 700,
  },
  {
    module: "Students",
    moduleKey: "student",
    action: "Create",
    actionKey: "create",
    permissionKey: "student.create",
    description: "Can create students",
    menuGroup: "Student Management",
    isMenuPermission: false,
    displayOrder: 701,
  },
  {
    module: "Students",
    moduleKey: "student",
    action: "Edit",
    actionKey: "edit",
    permissionKey: "student.edit",
    description: "Can edit students",
    menuGroup: "Student Management",
    isMenuPermission: false,
    displayOrder: 702,
  },
  {
    module: "Students",
    moduleKey: "student",
    action: "Delete",
    actionKey: "delete",
    permissionKey: "student.delete",
    description: "Can delete students",
    menuGroup: "Student Management",
    isMenuPermission: false,
    displayOrder: 703,
  },
  {
    module: "Students",
    moduleKey: "student",
    action: "Export",
    actionKey: "export",
    permissionKey: "student.export",
    description: "Can export students",
    menuGroup: "Student Management",
    isMenuPermission: false,
    displayOrder: 704,
  },
  {
    module: "Students",
    moduleKey: "student",
    action: "Bulk Update",
    actionKey: "bulk_update",
    permissionKey: "student.bulk_update",
    description: "Can perform student bulk updates",
    menuGroup: "Student Management",
    isMenuPermission: false,
    displayOrder: 705,
  },
  {
    module: "Students",
    moduleKey: "student",
    action: "Promote",
    actionKey: "promote",
    permissionKey: "student.promote",
    description: "Can promote students",
    menuGroup: "Student Management",
    isMenuPermission: false,
    displayOrder: 706,
  },

  {
    module: "Student Field Configuration",
    moduleKey: "student_field_config",
    action: "View",
    actionKey: "view",
    permissionKey: "student_field_config.view",
    description: "Can view student field configuration",
    menuGroup: "Student Management",
    isMenuPermission: true,
    displayOrder: 750,
  },
  {
    module: "Student Field Configuration",
    moduleKey: "student_field_config",
    action: "Edit",
    actionKey: "edit",
    permissionKey: "student_field_config.edit",
    description: "Can edit student field configuration",
    menuGroup: "Student Management",
    isMenuPermission: false,
    displayOrder: 751,
  },

  {
    module: "Attendance",
    moduleKey: "attendance",
    action: "View",
    actionKey: "view",
    permissionKey: "attendance.view",
    description: "Can view attendance",
    menuGroup: "Attendance",
    isMenuPermission: true,
    displayOrder: 800,
  },
  {
    module: "Attendance",
    moduleKey: "attendance",
    action: "Mark",
    actionKey: "mark",
    permissionKey: "attendance.mark",
    description: "Can mark student attendance",
    menuGroup: "Attendance",
    isMenuPermission: false,
    displayOrder: 801,
  },
  {
    module: "Attendance",
    moduleKey: "attendance",
    action: "Edit",
    actionKey: "edit",
    permissionKey: "attendance.edit",
    description: "Can edit student attendance",
    menuGroup: "Attendance",
    isMenuPermission: false,
    displayOrder: 802,
  },
  {
    module: "Attendance",
    moduleKey: "attendance",
    action: "Export",
    actionKey: "export",
    permissionKey: "attendance.export",
    description: "Can export attendance",
    menuGroup: "Attendance",
    isMenuPermission: false,
    displayOrder: 803,
  },
]);

export const ALL_PERMISSION_KEYS = Object.freeze(
  PERMISSIONS.map((permission) => permission.permissionKey)
);